/*
  # Missing Tables Migration

  This migration creates tables that were missing from the new Supabase project.

  1. New Tables
    - `consultation_conversations` - AI consultation session records
    - `consultation_messages` - Individual messages within consultations
    - `google_drive_tokens` - Google OAuth tokens for audio file access
    - `user_audio_files` - Audio file metadata linked to Google Drive
    - `policy_history` - Learning policy history generated by AI coach

  2. Security
    - RLS enabled on all tables
    - Users can only access their own data
*/

-- consultation_conversations
CREATE TABLE IF NOT EXISTS consultation_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type text NOT NULL CHECK (type IN ('general', 'grammar')),
  title text NOT NULL DEFAULT 'New Conversation',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE consultation_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own conversations"
  ON consultation_conversations FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own conversations"
  ON consultation_conversations FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own conversations"
  ON consultation_conversations FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own conversations"
  ON consultation_conversations FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_consultation_conversations_user_id ON consultation_conversations(user_id);

-- consultation_messages
CREATE TABLE IF NOT EXISTS consultation_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid REFERENCES consultation_conversations(id) ON DELETE CASCADE NOT NULL,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE consultation_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view messages from own conversations"
  ON consultation_messages FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM consultation_conversations
      WHERE consultation_conversations.id = consultation_messages.conversation_id
      AND consultation_conversations.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert messages to own conversations"
  ON consultation_messages FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM consultation_conversations
      WHERE consultation_conversations.id = consultation_messages.conversation_id
      AND consultation_conversations.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete messages from own conversations"
  ON consultation_messages FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM consultation_conversations
      WHERE consultation_conversations.id = consultation_messages.conversation_id
      AND consultation_conversations.user_id = auth.uid()
    )
  );

CREATE INDEX IF NOT EXISTS idx_consultation_messages_conversation_id ON consultation_messages(conversation_id);

-- google_drive_tokens
CREATE TABLE IF NOT EXISTS google_drive_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expiry timestamptz NOT NULL,
  folder_id text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE google_drive_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own Google Drive tokens"
  ON google_drive_tokens FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own Google Drive tokens"
  ON google_drive_tokens FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own Google Drive tokens"
  ON google_drive_tokens FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own Google Drive tokens"
  ON google_drive_tokens FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_google_drive_tokens_user_id ON google_drive_tokens(user_id);

-- user_audio_files
CREATE TABLE IF NOT EXISTS user_audio_files (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  file_name text NOT NULL,
  google_drive_file_id text NOT NULL,
  file_url text NOT NULL,
  file_size bigint NOT NULL,
  mime_type text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE user_audio_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own audio files"
  ON user_audio_files FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own audio files"
  ON user_audio_files FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own audio files"
  ON user_audio_files FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own audio files"
  ON user_audio_files FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_user_audio_files_user_id ON user_audio_files(user_id);

-- policy_history
CREATE TABLE IF NOT EXISTS policy_history (
  policyid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL REFERENCES public.users(email) ON DELETE CASCADE,
  createdat date DEFAULT CURRENT_DATE,
  triggertype text,
  policytext text,
  policysummary text,
  focusskills text,
  basedlevel text,
  userreaction integer CHECK (userreaction >= 1 AND userreaction <= 5),
  isactive boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE policy_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own policy history"
  ON policy_history FOR SELECT
  TO authenticated
  USING (
    email IN (SELECT email FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "Users can insert own policy history"
  ON policy_history FOR INSERT
  TO authenticated
  WITH CHECK (
    email IN (SELECT email FROM public.users WHERE id = auth.uid())
  );

CREATE POLICY "Users can update own policy history"
  ON policy_history FOR UPDATE
  TO authenticated
  USING (email IN (SELECT email FROM public.users WHERE id = auth.uid()))
  WITH CHECK (email IN (SELECT email FROM public.users WHERE id = auth.uid()));

CREATE POLICY "Users can delete own policy history"
  ON policy_history FOR DELETE
  TO authenticated
  USING (email IN (SELECT email FROM public.users WHERE id = auth.uid()));

CREATE INDEX IF NOT EXISTS idx_policy_history_email ON policy_history(email);
CREATE INDEX IF NOT EXISTS idx_policy_history_createdat ON policy_history(createdat DESC);

-- Trigger functions for updated_at
CREATE OR REPLACE FUNCTION update_consultation_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_consultation_conversations_updated_at ON consultation_conversations;
CREATE TRIGGER update_consultation_conversations_updated_at
  BEFORE UPDATE ON consultation_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_consultation_updated_at();
